### ISSUE TITLE
requests-ntlm2 should not rely on six.py in urllib3

### ISSUE THREAD

**Issue by jkugler** [dopstar/requests-ntlm2#17]
requests-ntlm2 relies on an embedded copy of six.py being in urllib3.  However, Debian/Ubuntu (and maybe others) remove this package, and modify urllib3 to use the system six installation. This causes an error when trying to use requests-ntlm2:
```
$ python3 -c 'from requests_ntlm2 import HttpNtlmAuth'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/requests_ntlm2/__init__.py", line 1, in <module>
    from .adapters import HttpNtlmAdapter, HttpProxyAdapter
  File "/usr/local/lib/python3.8/dist-packages/requests_ntlm2/adapters.py", line 10, in <module>
    from .connection import HTTPConnection as _HTTPConnection
  File "/usr/local/lib/python3.8/dist-packages/requests_ntlm2/connection.py", line 9, in <module>
    from requests.packages.urllib3.packages.six.moves.http_client import (
ModuleNotFoundError: No module named 'requests.packages.urllib3.packages.six'
```
Instead, I propose adding `six` to the requirements in setup.py, and import that instead.

**Comment by dopstar** [comment]
> Instead, I propose adding six to the requirements in setup.py, and import that instead.

fair enough. you can send the pr, or i can address this next week

**Comment by jkugler** [comment]
Excellent! When might a new version be found at https://pypi.org/project/requests-ntlm2/ ?

**Comment by dopstar** [comment]
its now in pypi, version 6.2.7

**Comment by jkugler** [comment]
You rock! Thank you so much!
