### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by rohitbhio** [dopstar/requests-ntlm2#6]
File "/data/miniconda3/lib/python3.7/site-packages/requests_ntlm2/connection.py", line 45, in _get_header_bytes
    http_connect_string = b"CONNECT {}:{} HTTP/1.0\r\n".format(host, port)

AttributeError: 'bytes' object has no attribute 'format'

**Comment by dopstar** [comment]
thanks for reporting the bug, upgrade to version 6.0.8 or later:

```shell
pip install 'requests-ntlm2>=6.0.8' 
```
